[package]
name = "rust_audio_process_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
numpy = "0.18.2"
ndarray = "0.15.6"

[lib]
name = "rust_audio_process_lib"
crate-type = ["cdylib"]
